#modeling the expert
quality = read.csv("quality.csv")
str(quality)
table(quality$PoorCare)
library(caTools)
set.seed(88)
split = sample.split(quality$PoorCare,SplitRatio=0.75)
split
qualityTrain = subset(quality, split ==TRUE)
qualityTest = subset(quality,split == FALSE)
QualityLog = glm(PoorCare~OfficeVisits+Narcotics, data=qualityTrain, family=binomial)
summary(QualityLog)
predictTrain = predict(QualityLog, type = "response")
summary(predictTrain)
tapply(predictTrain, qualityTrain$PoorCare, mean)
QLog = glm(PoorCare~StartedOnCombination+ProviderCount, data=qualityTrain, family=binomial)
summary(QLog)
table(qualityTrain$PoorCare, predictTrain>0.5)
library("ROCR")
ROCRpred = prediction(predictTrain, qualityTrain$PoorCare)
ROCRperf = performance(ROCRpred,"tpr","fpr")
plot(ROCRperf,colorize= TRUE,print.cutoffs.at=seq(0,1,0.1),text.adj=c(-0.2,1.7))
predictTest = predict(QualityLog, type="response", newdata=qualityTest)
ROCRpredTest = prediction(predictTest, qualityTest$PoorCare)
auc = as.numeric(performance(ROCRpredTest, "auc")@y.values)


#THE FRAMINGHAM HEART STUDY
framingham= read.csv("framingham.csv")
set.seed(1000)
split=sample.split(framingham$TenYearCHD, SplitRatio = 0.65)
train = subset(framingham,split==TRUE)
test = subset(framingham,split ==FALSE)
framinghamLog=glm(TenYearCHD~., data = train, family = binomial)
predictTest=predict(framinghamLog, type = "response",newdata=test)
table(test$TenYearCHD,predictTest>0.5)
ROCRpred= prediction(predictTest,test$TenYearCHD)
as.numeric(performance(ROCRpred, "auc")@y.values)

#recitation
polling = read.csv("PollingData.csv")
install.packages("mice")
library("mice")
simple = polling[c("Rasmussen","SurveyUSA","PropR","DiffCount")]
summary(simple)
set.seed(144)
imputed= complete(mice(simple))
polling$Rasmussen = imputed$Rasmussen
polling$SurveyUSA = imputed$SurveyUSA
Train = subset(polling,Year == 2004|Year == 2008)
Test = subset(polling,Year == 2012)
mod1 = glm(Republican~PropR,data=Train, family ="binomial")
pred1 = predict(mod1, type ="response")
table(Train$Republican, pred1 >=0.5)
mod2 = glm(Republican~SurveyUSA+DiffCount,data=Train, family ="binomial")
pred2 = predict(mod1, type ="response")
table(Train$Republican, pred2 >=0.5)
table(Test$Republican, sign(Test$Rasmussen))
TestPrediction = predict(mod2, newdata=Test,type="response")
table(Test$Republican,TestPrediction>=0.5)

#homework
#POPULARITY OF MUSIC RECORDS
songs = read.csv("songs.csv")
sum(songs$year==2010)
table(songs$year)
table(songs$artistname)
MichaelJackson = subset(songs, artistname == "Michael Jackson")
str(MichaelJackson)
top10= subset(MichaelJackson, Top10==1)
top10$songtitle
MichaelJackson[c('songtitle', 'Top10')]
summary(songs$timesignature)
str(songs$timesignature)
table(songs$timesignature)
summary(songs$tempo)
songs$songtitle[which.max(songs$tempo)]
SongsTrain = subset(songs, year<=2009)
SongsTest = subset(songs, year>2009)
nrow(SongsTrain)
nonvars = c("year", "songtitle", "artistname", "songID", "artistID")
SongsTrain = SongsTrain[,!(names(SongsTrain)%in%nonvars)]
SongsTest = SongsTest[ , !(names(SongsTest) %in% nonvars) ]
SongsLog1=glm(Top10~.,data=SongsTrain, family=binomial)
summary(SongsLog1)
cor(SongsTrain$loudness,SongsTrain$energy)
SongsLog2 = glm(Top10 ~ . - loudness, data=SongsTrain, family=binomial)
summary(SongsLog2)
SongsLog3 = glm(Top10 ~ . - energy, data=SongsTrain, family=binomial)
summary(SongsLog3)
pred3 = predict(SongsLog3,newdata=SongsTest,type="response" )
table(SongTest$Top10,pred3>0.45)
accuracy=(309+19)/(309+5+19+40)
accuracy
table(SongsTest$Top10)
Test2010= subset(SongTest,year==2010)
pred2010 = predict(SongsLog3,newdata=Test2010,type="response" )
table(Test2010$Top10,pred2010>0.45)
specificity=309/(309+5)
sensitivity = 19/(19+40)

#PREDICTING PAROLE VIOLATORS
parole=read.csv("parole.csv")
str(parole)
sum(parole$violator)
parole$state = as.factor(parole$state)
parole$crime = as.factor(parole$crime)
set.seed(144)
library(caTools)
split=sample.split(parole$violator,SplitRatio = 0.7)
train = subset(parole,split==TRUE)
test = subset(parole,split==FALSE)
paroleLog= glm(violator~., data=train, family="binomial")
summary(paroleLog)
predTest= predict(paroleLog, newdata=test,type="response")
summary(predTest)
table(test$violator,predTest>0.5)
library("ROCR")
pred = prediction(predTest, test$violator)
as.numeric(performance(pred, "auc")@y.values)

#PREDICTING LOAN REPAYMENT
loans= read.csv("loans.csv")
str(loans)
mean(loans$not.fully.paid)
summary(loans)
library(mice)
set.seed(144)
vars.for.imputation = setdiff(names(loans), "not.fully.paid")
imputed = complete(mice(loans[vars.for.imputation]))
loans[vars.for.imputation] = imputed
loans_imputed=read.csv("loans_imputed.csv")
summary(loans_imputed)
set.seed(144)
split=sample.split(loans$not.fully.paid,SplitRatio = 0.7)
train = subset(loans,split==TRUE)
test = subset(loans, split==FALSE)
nfp=glm(not.fully.paid~.,data=train,family="binomial")
predicted.risk = predict(nfp, newdata = test,type = "response")
table(test$not.fully.paid,predicted.risk>0.5)
test$predicted.risk=predicted.risk
library(ROCR)
pred = prediction(test$predicted.risk, test$not.fully.paid)
as.numeric(performance(pred, "auc")@y.values)
nfp2 = glm(not.fully.paid~int.rate,data=train, family="binomial")
predicted.risk2 = predict(nfp2, newdata = test,type = "response")
summary(predicted.risk2)
prediction.bivariate = prediction(predicted.risk2, test$not.fully.paid)
as.numeric(performance(prediction.bivariate, "auc")@y.values)
test$profit = exp(test$int.rate*3) - 1
test$profit[test$not.fully.paid == 1] = -1
highInterest = subset(test, int.rate >= 0.15) 
summary(highInterest$profit)
summary(highInterest$profit)
mean(highInterest$not.fully.paid)
cutoff = sort(highInterest$predicted.risk, decreasing=FALSE)[100]
selectedLoans = subset(highInterest, predicted.risk <= cutoff) 
sum(selectedLoans$profit)
table(selectedLoans$not.fully.paid) 
