mvt <- read.csv("mvtWeek1.csv")
str(mvt)
max(mvt$ID)
min(mvt$Beat)
DateConvert = as.Date(strptime(mvt$Date, "%m/%d/%y %H:%M"))
mvt$Month = months(DateConvert)
mvt$Weekday = weekdays(DateConvert)
mvt$Date = DateConvert
hist(mvt$Date, breaks=100)
boxplot(mvt$Date ~ mvt$Arrest)
WHO <- read.csv("WHO.csv")
mean(WHO$Over60)
which.min(WHO$Over60)
WHO$Country[183]
which.max(WHO$LiteracyRate)
WHO$Country[44]
tapply(WHO$ChildMortality, WHO$Region, mean)
#Recitation Nutritional Education
USDA = read.csv("USDA.csv")
str(USDA)
summary(USDA)
which.max(USDA$Sodium)
names(USDA)
USDA$Description[265]
HighSodium = subset(USDA, Sodium>10000)
nrow(HighSodium)
HighSodium$Description
match("CAVIAR", USDA$Description)
USDA$Sodium[4154]
plot(USDA$Protein,USDA$TotalFat, xlab ="Protein",ylab="Fat",main="Protein vs Fat", col = "red")
hist(USDA$VitaminC, xlab = "Vitamin C (mg)",main="Histogram of Vitamin C Levels", xlim = c(0,100),breaks = 2000)
boxplot(USDA$Sugar,main = "Boxplot of Sugar Levels", ylab = "Sugar (g)")
HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
str(HighSodium)
USDA$HighSodium = HighSodium
USDA$HighProtein = as.numeric(USDA$Protein > mean(USDA$Protein, na.rm=TRUE))
USDA$HighFat = as.numeric(USDA$TotalFat > mean(USDA$TotalFat, na.rm=TRUE))
USDA$HighCarbs = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate, na.rm=TRUE))
table(USDA$HighSodium, USDA$HighFat)
tapply(USDA$Iron,USDA$HighProtein, mean, na.rm=TRUE)
tapply(USDA$VitaminC,USDA$HighCarb, max, na.rm=TRUE)
tapply(USDA$VitaminC,USDA$HighCarb, summary, na.rm=TRUE)
#Assignment Stock Dynamics
IBM = read.csv("IBMStock.csv")
GE = read.csv("GEStock.csv")
ProcterGamble = read.csv("ProcterGambleStock.csv")
CocaCola = read.csv("CocaColaStock.csv")
Boeing = read.csv("BoeingStock.csv")
IBM$Date = as.Date(IBM$Date, "%m/%d/%y")
GE$Date = as.Date(IBM$Date, "%m/%d/%y")
CocaCola$Date = as.Date(IBM$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(IBM$Date, "%m/%d/%y")
Boeing$Date = as.Date(IBM$Date, "%m/%d/%y")
summary(Boeing$Date)
mean(IBM$StockPrice)
min(GE$StockPrice)
max(CocaCola$StockPrice)
median(Boeing$StockPrice)
sd(ProcterGamble$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice,col="red",type="l")
lines(ProcterGamble$Date, ProcterGamble$StockPrice,col="blue",lty=2)
abline(v=as.Date(c("2000-03-01")),lwd=2)
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], lty=2, col="blue", ylim=c(0,210))
lines(IBM$Date[301:432], IBM$StockPrice[301:432], lty=3, col="green", ylim=c(0,210))
lines(GE$Date[301:432], GE$StockPrice[301:432], lty=4, col="orange", ylim=c(0,210))
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], lty=5, col="purple", ylim=c(0,210))
abline(v=as.Date(c("1997-09-01")),lwd=0)
abline(v=as.Date(c("1997-11-01")),lwd=1)
tapply(IBM$StockPrice,months(IBM$Date),mean)
mean(IBM$StockPrice)
sort(tapply(GE$StockPrice,months(GE$Date),mean))
sort(tapply(CocaCola$StockPrice,months(CocaCola$Date),mean))
CPS <-read.csv("CPSData.csv")
#DEMOGRAPHICS AND EMPLOYMENT IN THE UNITED STATES
str(CPS)
sort(table(CPS$Industry))
sort(table(CPS$State)) 
table(CPS$Citizenship)
table(CPS$Hispanic,CPS$Race)
table(CPS$Race,CPS$Hispanic)
table(CPS$Age, is.na(CPS$Married))
table(CPS$State, is.na(CPS$MetroAreaCode))
table(CPS$Region, is.na(CPS$MetroAreaCode))
sort(tapply( is.na(CPS$MetroAreaCode),CPS$State,mean))
MetroAreaMap <- read.csv("MetroAreaCodes.csv")
CountryMap <- read.csv("CountryCodes.csv")
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
summary(CPS)
sum(is.na(CPS$MetroArea))
sort(table(CPS$MetroArea))

sort(tapply(CPS$Hispanic,CPS$MetroArea,mean))
sort(tapply(CPS$Race=="Asian",CPS$MetroArea,mean))
sort(tapply(CPS$Education == "Doctorate degree", CPS$MetroArea, mean,na.rm=TRUE))
CPS = merge(CPS, CountryMap, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
table(CPS$MetroArea.y == "New York-Northern New Jersey-Long Island, NY-NJ-PA", CPS$Country!= "United States")
sort(tapply(CPS$Country=="India", CPS$MetroArea.y,sum,na.rm=TRUE))
sort(tapply(CPS$Country=="Brazil", CPS$MetroArea.y,sum,na.rm=TRUE))
sort(tapply(CPS$Country=="Somalia", CPS$MetroArea.y,sum,na.rm=TRUE))




#Assignment 1 INTERNET PRIVACY POLL
poll<-read.csv("AnonymityPoll.csv")
summary(poll)
table(poll$Smartphone)
